---
# group_vars/all.yml
docker_repo_base_url: "https://mirrors.huaweicloud.com/docker-ce"

### Common Variables
k8s_version: "1.34.2"

### Plugins Variables
k8s_plugin_metallb_ip_address_pool_default:
  - "10.17.3.240-10.17.3.250" # adjust with yours

k8s_plugin_manifest_proxy: "https://ghproxy.net"
