---
- name: Install Kubernetes plugins
  hosts: controllers
  gather_facts: true
  roles:
    - role: plugin

# An example: how to install specified plugins
# ansible-playbook -i inventory.ini playbook-plugins.yml   -e "k8s_plugins_only=cni-calico,metallb,metrics-server"
