---
# playbook-devops.yml
- name: "Deploy DevOps tools on Kubernetes"
  hosts: controllers
  gather_facts: true
  vars:
    k8s_plugins_only:
      - gitlab
      - openproject
  roles:
    - role: plugin
