---
- name: Prepare Kubernetes cluster
  hosts: k8s_cluster
  become: yes
  roles:
    - role: prerequisite
      tags: prerequisite
    - role: containerd
      tags: containerd
    - role: kubernetes
      tags: kubernetes
  tags: prepare

- name: Initialize Kubernetes cluster
  become: yes
  hosts: controllers
  roles:
    - initialize
  tags: initialize

- name: Join worker nodes to cluster
  hosts: workers
  roles:
    - join
  tags: join

- name: Install Kubernetes plugins
  hosts: controllers
  roles:
    - plugin
  tags: plugin