---
- name: Prepare Kubernetes cluster
  hosts: k8s_cluster
  become: yes
  roles:
    - role: prerequisite
      tags: prerequisite
    - role: containerd
      tags: containerd
    - role: kubernetes
      tags: kubernetes
  tags: prepare

- name: Initialize Kubernetes master
  become: yes
  hosts: masters
  roles:
    - master
  tags: master

- name: Join worker nodes to cluster
  hosts: workers
  roles:
    - worker
  tags: worker

- name: Install Kubernetes plugins
  hosts: masters
  roles:
    - plugin
  tags: plugin