---
- name: Reset Kubernetes cluster
  hosts: k8s_cluster
  become: yes
  tasks:
    - name: Reset kubeadm
      command: kubeadm reset -f
      ignore_errors: yes

    - name: Remove CNI configuration
      file:
        path: /etc/cni/net.d
        state: absent
      ignore_errors: yes

    - name: Clean up HOME kube config
      file:
        path: "{{ ansible_env.HOME }}/.kube"
        state: absent
      ignore_errors: yes

    - name: Flush iptables rules
      shell: |
        iptables -F &&
        iptables -t nat -F &&
        iptables -t mangle -F &&
        iptables -X
      ignore_errors: yes

    - name: Check if IPVS rules exist
      command: ipvsadm -Ln
      register: ipvs_rules
      changed_when: false
      failed_when: false

    - name: Clear IPVS rules
      command: ipvsadm --clear
      when: ipvs_rules.stdout != ""
      failed_when: false

    - name: Clean up flannel interface
      command: ip link delete cni0
      ignore_errors: yes
      when: ansible_facts['interfaces'] is defined and 'cni0' in ansible_facts['interfaces']
