---
- name: Check if node is already joined to cluster
  shell: "kubectl get node {{ inventory_hostname }} >/dev/null"
  delegate_to: "{{ groups['controllers'][0] }}"
  register: node_check_result
  changed_when: false
  ignore_errors: true

- block:
  - name: Get join command from controller
    command: >
      kubeadm token create --print-join-command
    delegate_to: "{{ groups['controllers'][0] }}"
    register: join_command
    failed_when: false

  - name: Display join command
    debug:
      msg: "{{ join_command.stdout }}"
    when: k8s_display_join_command | default(false) | bool

  - name: Join worker to cluster
    become: yes
    command: "{{ join_command.stdout }}"
  when: node_check_result.rc != 0

- name: Wait for node to be ready
  command: >
    kubectl wait --for=condition=Ready node/{{ inventory_hostname | quote }} --timeout={{ k8s_wait_node_ready_timeout }}
  delegate_to: "{{ groups['controllers'][0] }}"
  register: wait_result
  retries: 3
  delay: 10
  until: wait_result.rc == 0
  failed_when: wait_result.rc != 0 and 'timeout' not in wait_result.stderr
  tags: wait-node-ready
