---
docker_distro_mapping:
  rocky: centos
  almalinux: centos

docker_distro: "{{ docker_distro_mapping[ansible_facts['distribution'] | lower] | default(ansible_facts['distribution'] | lower) }}"

docker_repo: "https://download.docker.com/linux/{{ docker_distro }}/docker-ce.repo"

containerd_required_packages:
  Debian:
    # refer to https://docs.docker.com/engine/install/debian/
    # refer to https://docs.docker.com/engine/install/ubuntu/
    - ca-certificates
    - curl
  RedHat:
    # refer to https://docs.docker.com/engine/install/centos/
    # refer to https://docs.docker.com/engine/install/fedora/
    - dnf-plugins-core

containerd_registry_mirror_enabled: true
containerd_registry_mirror_skip_verify: true
containerd_registry_mirror_config_path: "/etc/containerd/certs.d"
containerd_registry_mirrors:
  "docker.io":
    - "https://docker.xuanyuan.me"
    - "https://docker.1ms.run"
    - "https://docker.m.daocloud.io"
  "registry.k8s.io":
    - "https://k8s.m.daocloud.io"
