---
docker_distro_mapping:
  rocky: centos
  almalinux: centos

containerd_required_packages:
  Debian: 
    # refer to https://docs.docker.com/engine/install/debian/
    # refer to https://docs.docker.com/engine/install/ubuntu/
    - ca-certificates
    - curl
  RedHat: 
    # refer to https://docs.docker.com/engine/install/centos/
    # refer to https://docs.docker.com/engine/install/fedora/
    - dnf-plugins-core