---
- name: Gather facts
  ansible.builtin.setup:
  when: ansible_facts["os_family"] is not defined

- name: Check if Kubernetes components installed
  ansible.builtin.shell: |
    if command -v kubeadm >/dev/null 2>&1; then
      kubeadm version --output short
      exit 0
    else
      echo "Kubernetes components not installed on {{ inventory_hostname }}"
      exit 1
    fi
  register: kubeadm_version_check
  changed_when: false
  failed_when: false

- name: Install Kubernetes components if not present
  when: kubeadm_version_check.rc != 0
  block:
    - name: Install required packages
      ansible.builtin.package:
        name: "{{ k8s_required_packages[ansible_facts['os_family']] }}"
        state: present
        update_cache: true

    - name: Setup Kubernetes's repository
      ansible.builtin.include_tasks:
        file: setup-repo-{{ ansible_facts["os_family"] | lower }}.yml

    - name: Install Kubernetes components on Debian-based systems
      ansible.builtin.apt:
        name:
          - kubelet={{ k8s_major_minor }}.*
          - kubeadm={{ k8s_major_minor }}.*
          - kubectl={{ k8s_major_minor }}.*
        state: present
      when: ansible_facts["os_family"] == "Debian"

    - name: Install Kubernetes components with disableexcludes on RedHat-based systems
      ansible.builtin.dnf:
        name:
          - kubelet-{{ k8s_version }}
          - kubeadm-{{ k8s_version }}
          - kubectl-{{ k8s_version }}
          - kubernetes-cni-{{ k8s_cni_pkg_version }}
        state: present
        disable_excludes: kubernetes
      when: ansible_facts["os_family"] == "RedHat"

    - name: Hold Kubernetes packages at current version on Debian-based systems
      ansible.builtin.dpkg_selections:
        name: "{{ item }}"
        selection: hold
      loop:
        - kubelet
        - kubeadm
        - kubectl
      when: ansible_facts["os_family"] == "Debian"

    - name: Hold Kubernetes packages on RedHat-based systems
      when: ansible_facts["os_family"] == "RedHat"
      block:
        - name: Ensure the DNF Version Lock plugin is installed
          ansible.builtin.package:
            name: python3-dnf-plugin-versionlock
            state: present
            update_cache: true
        - name: Hold Kubernetes packages at current version on RedHat-based systems
          ansible.builtin.shell: |
            for pkg in kubelet kubeadm kubectl; do
              yum versionlock add $pkg
            done
          args:
            executable: /bin/bash
          changed_when: false

    - name: Create a dedicated Kubernetes resolv.conf to prevent CoreDNS loops
      ansible.builtin.copy:
        dest: "{{ k8s_resolv_conf }}"
        content: |
          # Generated by Ansible for Kubernetes Kubelet
          search {{ k8s_search_domain | default('cluster.local') }}
          {% for dns in k8s_dedicated_dns %}
          nameserver {{ dns }}
          {% endfor %}
          options edns0 trust-ad
        mode: '0644'
      when: k8s_use_dedicated_dns | default('false') | bool

    - name: Configure Kubelet to use expected resolv.conf file
      ansible.builtin.lineinfile:
        path: "{{ k8s_kubelet_config_path[ansible_facts['os_family']] }}"
        regexp: '^KUBELET_EXTRA_ARGS='
        line: 'KUBELET_EXTRA_ARGS="--resolv-conf={{ k8s_resolv_conf | trim }}"'
        create: true
        mode: '0644'

- name: Ensure kubelet is running and enabled
  ansible.builtin.systemd:
    name: containerd
    state: started
    enabled: true
