---
- name: Check if Kubernetes is already installed
  shell: "command -v kubeadm >/dev/null && kubeadm version"
  register: kubeadm_version_check
  changed_when: false
  ignore_errors: true
  tags: kubernetes

- block:
  - name: Install required packages
    package:
      name: "{{ system_required_packages[ansible_os_family] }}"
      state: present
      update_cache: true

  - name: Setup Kubernetes's repository
    include_tasks:
      file: setup-repo-{{ ansible_os_family | lower }}.yml

  - name: Install Kubernetes components on Debian-based systems
    apt:
      name:
        - kubelet={{ k8s_major_minor }}.*
        - kubeadm={{ k8s_major_minor }}.*
        - kubectl={{ k8s_major_minor }}.*
      state: present
      update_cache: yes
    when: ansible_os_family == "Debian"
    
  - name: Install Kubernetes components with disableexcludes on RedHat-based systems
    yum:
      name:
        - kubelet-{{ k8s_version }}
        - kubeadm-{{ k8s_version }}
        - kubectl-{{ k8s_version }}
      state: present
      disable_excludes: kubernetes
    when: ansible_os_family == "RedHat"

  - name: Hold Kubernetes packages at current version on Debian-based systems
    command: apt-mark hold kubelet kubeadm kubectl
    when: ansible_os_family == "Debian"

  - name: Hold Kubernetes packages at current version on RedHat-based systems
    shell: |
      for pkg in kubelet kubeadm kubectl; do
        yum versionlock add $pkg
      done
    args:
      executable: /bin/bash
    when: ansible_os_family == "RedHat"

  - name: Start and enable kubelet service
    systemd:
      name: kubelet
      state: started
      enabled: yes
      daemon_reload: yes
  when: kubeadm_version_check.rc != 0
  tags: kubernetes
