---
- name: Check if Kubernetes repository file exists
  ansible.builtin.stat:
    path: /etc/apt/sources.list.d/kubernetes.list
  register: k8s_repo_file

- block:
    - name: Create Kubernetes keyring directory
      ansible.builtin.file:
        path: /etc/apt/keyrings
        state: directory
        mode: "0755"

    - name: Download Kubernetes GPG key
      ansible.builtin.shell: |
        set -o pipefail
        curl -fsSL https://pkgs.k8s.io/core:/stable:/v{{ k8s_major_minor }}/deb/Release.key | gpg --yes --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg
        chmod 0644 /etc/apt/keyrings/kubernetes-apt-keyring.gpg
      args:
        creates: /etc/apt/keyrings/kubernetes-apt-keyring.gpg
        executable: /bin/bash
      retries: 3
      delay: 5

    - name: Add Kubernetes repository
      ansible.builtin.blockinfile:
        path: /etc/apt/sources.list.d/kubernetes.list
        block: |
          deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v{{ k8s_major_minor }}/deb/ /
        marker: "# {mark} ANSIBLE MANAGED KUBERNETES REPO"
        create: true
        backup: true

    - name: Force update apt package cache
      ansible.builtin.apt:
        update_cache: true
        force_apt_get: true
  when: not k8s_repo_file.stat.exists
