---
- name: Check if Docker repository file exists
  ansible.builtin.stat:
    path: "{{ k8s_yum_repo_file }}"
  register: k8s_repo_file

- name: Setup Kubernetes repository
  when: not k8s_repo_file.stat.exists
  block:
    - name: Add Kubernetes YUM repository
      ansible.builtin.copy:
        dest: "{{ k8s_yum_repo_file }}"
        content: |
          [kubernetes]
          name=Kubernetes
          baseurl=https://pkgs.k8s.io/core:/stable:/v{{ k8s_major_minor }}/rpm/
          enabled=1
          gpgcheck=1
          gpgkey=https://pkgs.k8s.io/core:/stable:/v{{ k8s_major_minor }}/rpm/repodata/repomd.xml.key
          exclude=kubelet kubeadm kubectl cri-tools kubernetes-cni
        mode: "0644"

    - name: Dnf make cache
      ansible.builtin.dnf:
        update_cache: true
      ignore_errors: false
