---
# Helm version to install
helm_version: "3.16.4"

# Operating system platform (e.g., linux, darwin, windows)
helm_platform: "{{ ansible_facts['system'] | lower }}"

# CPU architecture (e.g., amd64, arm64)
helm_architecture: >-
  {{
    {
      'x86_64': 'amd64',
      'amd64': 'amd64',
      'aarch64': 'arm64',
      'arm64': 'arm64'
    }.get(ansible_facts['architecture'], ansible_facts['architecture']) | default('amd64')
  }}
