---
k8s_major_minor: "{{ (k8s_version.split('.') | list)[0:2] | join('.') }}"

k8s_required_packages:
  Debian:
    # refer to https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm/#k8s-install-0
    - apt-transport-https
    - ca-certificates
    - curl
    - gpg
  RedHat:
    # refer to https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm/#k8s-install-1
    - dnf-plugins-core

k8s_kubelet_config_path:
  Debian: /etc/default/kubelet
  RedHat: /etc/sysconfig/kubelet

k8s_use_dedicated_dns: false
k8s_dedicated_dns:
  - 8.8.8.8
  - 8.8.4.4

k8s_resolv_conf: >-
  {%- if k8s_use_dedicated_dns -%}
    /etc/kubernetes/resolv.conf
  {%- elif ansible_os_family == "Debian" -%}
    /run/systemd/resolve/resolv.conf
  {%- else -%}
    /etc/resolv.conf
  {%- endif -%}

k8s_yum_repo_file: "/etc/yum.repos.d/kubernetes.repo"

k8s_cni_pkg_version: "1.7.1"

k8s_gpg_fingerprint: "234654DA9A296436"   # Kubernetes core stable key
