---
- name: Check if Containerd is already installed
  ansible.builtin.shell: |
    if command -v containerd >/dev/null 2>&1; then
      containerd --version
      exit 0
    else
      echo "Containerd not installed on {{ inventory_hostname }}"
      exit 1
    fi
  register: containerd_version_check
  changed_when: false
  failed_when: false

- name: Install containerd if not present
  when: containerd_version_check.rc != 0
  block:
    - name: Gather facts
      ansible.builtin.setup:
      when: ansible_facts["os_family"] is not defined

    - name: Install required packages
      ansible.builtin.package:
        name: "{{ containerd_required_packages[ansible_facts['os_family']] }}"
        state: present
        update_cache: true

    - name: Setup Docker's repository
      ansible.builtin.include_tasks:
        file: setup-repo-{{ ansible_facts["os_family"] | lower }}.yml

    - name: Install containerd
      ansible.builtin.package:
        name: containerd.io
        state: present
      retries: 3
      delay: 15
      register: result
      until: result is succeeded

    - name: Configure containerd
      ansible.builtin.include_tasks:
        file: configure.yml

- name: Start and enable containerd service
  ansible.builtin.systemd:
    name: containerd
    state: started
    enabled: true
    daemon_reload: true
