---
# roles/containerd/tasks/main.yml

- name: Install containerd
  ansible.builtin.include_tasks:
    file: install.yml

- name: Configure containerd
  ansible.builtin.include_tasks:
    file: configure.yml

- name: Configure registry mirror(s)
  ansible.builtin.include_tasks:
    file: configure-registry-mirror.yml

- name: Ensure containerd is running and enabled
  ansible.builtin.systemd:
    name: containerd
    state: started
    enabled: true
