---
- name: Check if Containerd is already installed
  shell: |
    if command -v containerd >/dev/null 2>&1; then
      containerd --version
      exit 0
    else
      echo "Containerd not installed on {{ inventory_hostname }}"
      exit 1
    fi
  register: containerd_version_check
  changed_when: false
  failed_when: false

- block:
  - name: Gather facts
    setup:
    when: ansible_os_family is not defined

  - name: Install required packages
    package:
      name: "{{ containerd_required_packages[ansible_os_family] }}"
      state: present
      update_cache: true

  - name: Setup Docker's repository
    include_tasks:
      file: setup-repo-{{ ansible_os_family | lower }}.yml

  - name: Install containerd
    package:
      name: containerd.io
      state: present
    retries: 3
    delay: 10
    register: result
    until: result is succeeded

  - name: Configure containerd
    include_tasks:
      file: configure.yml
  when: containerd_version_check.rc != 0

- name: Start and enable containerd service
  systemd:
    name: containerd
    state: started
    enabled: yes
    daemon_reload: yes
