---
- name: Check if Docker repository file exists
  ansible.builtin.stat:
    path: /etc/yum.repos.d/docker-ce.repo
  register: docker_repo_file

- block:
    - name: Add Docker CE repository using dnf config-manager
      ansible.builtin.shell: |
        dnf-3 config-manager --add-repo https://download.docker.com/linux/{{ docker_distro_mapping[ansible_distribution | lower] | default(ansible_distribution | lower) }}/docker-ce.repo
      args:
        creates: /etc/yum.repos.d/docker-ce.repo
      register: repo_result
      changed_when:
        - "'added' in repo_result.stdout"
        - repo_result.rc == 0
      failed_when:
        - repo_result.rc != 0
        - "'already exists' not in repo_result.stderr"

    - name: Yum make cache
      ansible.builtin.yum:
        update_cache: true
      ignore_errors: false
  when: not docker_repo_file.stat.exists
